# Settings
cask_args appdir: '/Applications'

# Taps
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'buo/cask-upgrade'

# Brews
brew 'ack'
brew 'awscli'
brew 'bash'
brew 'cscope'
brew 'ctags'
brew 'dos2unix'
brew 'ffmpeg'
brew 'fish'
brew 'gdbm'
brew 'git'
brew 'gitmoji'
brew 'git-flow'
brew 'git-open'
brew 'git-town'
brew 'gpg'
brew 'httpie'
brew 'hugo'
brew 'macvim'
brew 'mas'
brew 'neofetch'
brew 'nmap'
brew 'node'
brew 'nvm'
brew 'openssl'
brew 'pcre'
brew 'python'
brew 'readline'
brew 'stow'
brew 'terraform'
brew 'typescript'
brew 'thefuck'
brew 'wget'
brew 'xz'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Casks
cask '1password'
cask 'appcleaner'
cask 'atom'
cask 'deluge'
cask 'docker' # non-cask doesn't install docker daemon!
cask 'firefox'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'kindle'
cask 'koala'
cask 'krita'
cask 'macdown'
cask 'postman'
cask 'telegram'
cask 'transmit'
cask 'tower'
cask 'visual-studio-code'
cask 'vmware-fusion'

# Java
cask 'java'
brew 'ant'
brew 'maven'
cask 'eclipse-ide'

# Fonts -- removed because homebrew's update will always pull these
# cask 'font-hack'
# cask 'font-source-code-pro-for-powerline'
# cask 'font-source-code-pro'
# cask 'font-input'
# cask 'font-source-sans-pro'
# cask 'font-source-serif-pro'
