[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

# [colors.primary]
# background = "0x1a1b26"
# foreground = "0xc0caf5"

[cursor]
# shape = "Block"
unfocused_hollow = true

[font]
size = 14.0
builtin_box_drawing = true

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[scrolling]
history = 10000

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_title = true
dynamic_padding = true
opacity = 1.0
blur = true
startup_mode = "Windowed"

[general]
live_config_reload = true
# import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/themes/tokyo-night-night.toml"]
# import = ["~/.config/alacritty/themes/one-dark.toml"]
