# Settings
cask_args appdir: '/Applications'

# Taps
tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'buo/cask-upgrade'

# Brews
brew 'ack'
# brew 'ant'
brew 'awscli'
brew 'bash'
brew 'cscope'
brew 'dos2unix'
brew 'ffmpeg'
brew 'fish'
brew 'gdbm'
brew 'git'
brew 'git-flow'
brew 'git-open'
brew 'git-town'
brew 'httpie'
brew 'hugo'
# brew 'jenv'
brew 'mas'
# brew 'maven'
brew 'nmap'
brew 'node'
brew 'neofetch'
brew 'openssl'
brew 'pcre'
brew 'python'
brew 'readline'
brew 'terraform'
brew 'thefuck'
brew 'wget'
brew 'xz'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Casks
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
# cask 'balsamiq-mockups'
# cask 'calibre'
cask 'deluge'
# cask 'discord'
# cask 'docker'
# cask 'doxie'
cask 'eclipse-java'
cask 'firefox'
# cask 'google-chrome'
# cask 'highsierramediakeyenabler'
# cask 'hyper'
cask 'java'
cask 'kaleidoscope'
# cask 'kindle'
cask 'koala'
casl 'krita'
cask 'macdown'
cask 'macvim'
cask 'postman'
# cask 'rescuetime'
cask 'sketch'
# cask 'slack'
# cask 'spotify'
# cask 'steam'
cask 'transmit'
cask 'tower'
cask 'visual-studio-code'
# cask 'vmware-fusion'

# Fonts -- removed because homebrew's update will always pull these
# cask 'font-source-code-pro-for-powerline'
# cask 'font-source-code-pro'
# cask 'font-input'
# cask 'font-source-sans-pro'
# cask 'font-source-serif-pro'
