# Taps
tap 'homebrew/bundle'
tap 'homebrew/command-not-found'
tap 'homebrew/cask'              # Only works on macOS
tap 'homebrew/cask-fonts'        # Only works on macOS
# tap 'koekeishiya/formulae'       # for yabai+skhd, only on macOS

# Brews
brew 'ack'                  # code search tool
brew 'ag'                   # another code search tool
# brew 'asdf'                 # toolchain versioner
brew 'autojump'             # jump to directories fast!
brew 'awscli'               # AWS cli client
brew 'bat'                  # a 'cat' replacement with syntax highlighting and paging
brew 'diff-so-fancy'        # a better diff
brew 'dos2unix'             # convert dos files to unix line endings
brew 'exa'                  # a replacement ls supporting git and tree
brew 'fasd'                 # a better find
brew 'fd'                   # a better find too
brew 'ffmpeg'               # audio/visual conversion tool
brew 'fish'                 # alternative shell (not POSIX compliant)
brew 'fortune'              # words of wisdom
brew 'fzf'                  # fuzzy file finder (shell and vim!)
# brew 'gh'                   # GitHub
brew 'git'                  # source control
brew 'go'                   # Go lang
brew 'git-flow'             # standard git workflows
brew 'gpg'                  # encryption utils
brew 'htop'                 # system stats
brew 'httpie'               # curl replacement
brew 'jq'                   # json formatter
brew 'jump'                 # directory jumper (see also autojump)
brew 'lua'                  # Scripting language, extraordinaire!
brew 'luarocks'             # Lua package manager
brew 'macos-trash'          # utility to leverage the trashcan from the shell
# brew 'trash-cli'            # linux equivalent of macos-trash
brew 'neofetch'             # graphical system summary
brew 'neovim'               # preferred vim
brew 'nmap'                 # port scanning util
brew 'noti'                 # macOS command line notification hook
brew 'nvm'                  # node version manager
brew 'openssl'              # ssl utilities
brew 'prettyping'           # a better ping
brew 'readline'             # dunno
brew 'ripgrep'              # a faster grep
brew 'rust'                 # Rust lang
# brew 'skhd'                 # keyboard shortcuts
brew 'starship'             # The best prompt for any shell
brew 'stow'                 # dotfile installation utility
brew 'thefuck'              # command correction utility
brew 'tldr'                 # a more concise man replacement
brew 'tmux'                 # terminal multiplexer (not yet used)
brew 'tmuxinator'           # tmux projects
brew 'tree'                 # directory tree
brew 'wget'                 # alternative shell web download util
# brew 'yabai'                # tiling window manager
brew 'yarn'                 # alternative to npm
brew 'youtube-dl'           # download youtube videos
brew 'zoxide'               # a better autojump & cd combined
brew 'zx'                   # javascript shell scripts

# zsh
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'zsh-you-should-use'

# Casks (Note: Only works on macOS)
cask '1password'              # password manager
cask 'alacritty'              # gpu accelerated terminal
cask 'alfred'                 # application launcher and more
cask 'appcleaner'             # clean uninstalls
# cask 'balenaetcher'           # USB ISO creator
# cask 'caldigit-docking-utility' # dock app
# cask 'calibre'                # ebook utilities
cask 'discord'                # alternate comms
cask 'docker'                 # container software
# cask 'figma'                  # design software
cask 'firefox'                # open source web browser
# cask 'github'                 # github client
cask 'hammerspoon'            # programmable mac automation
# cask 'iterm2'                 # a more feature-rich terminal
# cask 'kaleidoscope'           # Rich diffs
# cask 'karabiner-elements'     # low-level keyboard and mouse control
# cask 'krita'                  # open source paint app
# cask 'netnewswire'            # RSS feed reader
# cask 'openaudible'            # download / process audible content
cask 'postman'                # work with REST APIs
cask 'rectangle'              # window management
cask 'slack'                  # workplace comms
# cask 'typora'                 # markdown editor
cask 'visual-studio-code'     # Microsoft cross-platform editor

# Fonts
# Patched with nerd font support are good for Terminal but iTerm2 has built-in glyphs.
# Fonts would also include source-code-pro but that one will reinstall
# every brew update.
cask 'font-sf-pro'
cask 'font-sf-mono'
# cask 'font-sf-mono-for-powerline' # ligatures for SF Mono
cask 'font-cascadia-code'     # nerdfont: font-caskaydia-cove-nerd-font
cask 'font-dejavu'            # nerdfont: font-dejavu-sans-mono-nerd-font
cask 'font-fira-code'         # nerdfont: font-fira-code-nerd-font
cask 'font-fira-code-nerd-font'
cask 'font-jetbrains-mono'    # nerdfont: font-jetbrains-mono-nerd-font
cask 'font-hack'
cask 'font-hasklig'
# cask 'font-source-code-pro' # will always update if installed...
cask 'font-sauce-code-pro-nerd-font' # source code pro nerd font
