# General
abbr rm 'rm -i'
abbr cp 'cp -i'
abbr mv 'mv -i'
abbr mkdir 'mkdir -p'
abbr h 'history'
abbr fd 'fd -H'
abbr cat 'bat'
abbr top 'htop'
abbr nf 'neofetch'
abbr ping 'prettyping --nolegend'
abbr up 'uptime'
abbr vim 'nvim'
abbr yt 'youtube-dl'
abbr yt4 'youtube-dl --format mp4'
abbr ip 'dig +short myip.opendns.com @resolver1.opendns.com'
abbr diff 'diff-so-fancy'
abbr clean 'find . -name ".DS_Store" -print -delete'

## override git plugin's `gb` because I don't like the verbosity.
abbr gb 'git branch'
