require 'config.options'
require 'config.keymaps'
require 'config.plugins'
require 'config.colorscheme'
require 'config.cmp'
require 'config.lsp'
require 'config.telescope'
require 'config.treesitter'
